apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ame
  namespace: harus-edge
  labels:
    app: ame
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`ame.h.azusachino.icu`)
      kind: Rule
      services:
        - name: ame-platform
          port: 80
  # Uses the websecure entrypoint default cert (LE wildcard *.h.azusachino.icu).
  tls: {}
