[package]
name = "ame-learning-postgres"
version = "0.5.0"
edition = "2024"
publish = false

[dependencies]
ame-learning-application = { path = "../ame-learning-application" }
ame-learning-domain = { path = "../ame-learning-domain" }
async-trait = "0.1"
sqlx = { version = "0.8.3", features = ["runtime-tokio", "postgres", "uuid", "time", "json", "migrate"] }
serde_json = "1"
time = { version = "0.3", features = ["serde"] }
uuid = { version = "1", features = ["v7", "v4", "serde", "js"] }

[dev-dependencies]
tokio = { version = "1.43", features = ["full", "test-util"] }
