// Mock data for Harus
const QUIZZES = [
  {
    id: "qz_3kf2",
    title: "Macroeconomics: Monetary Policy",
    course: "ECON 204",
    author: "Dr. R. Halverson",
    questions: 18,
    duration: 35,
    difficulty: "Intermediate",
    tags: ["economics", "policy", "midterm-prep"],
    description: "Federal Reserve operations, interest rate transmission, and inflation targeting.",
    assigned: 142,
    completed: 98,
    avgScore: 73.2,
    updated: "2 days ago",
    color: "blue",
    status: "active",
  },
  {
    id: "qz_8sd1",
    title: "Algorithms — Graph Traversal",
    course: "CS 311",
    author: "Prof. M. Iwata",
    questions: 12,
    duration: 45,
    difficulty: "Advanced",
    tags: ["algorithms", "code", "graphs"],
    description: "BFS, DFS, topological sort, and complexity analysis.",
    assigned: 86,
    completed: 71,
    avgScore: 68.5,
    updated: "5 hours ago",
    color: "accent",
    status: "active",
  },
  {
    id: "qz_4mp9",
    title: "Organic Chemistry — Stereochemistry",
    course: "CHEM 220",
    author: "Dr. P. Okonkwo",
    questions: 24,
    duration: 50,
    difficulty: "Intermediate",
    tags: ["chemistry", "stereo", "isomers"],
    description: "Chirality, R/S nomenclature, and optical activity.",
    assigned: 203,
    completed: 188,
    avgScore: 81.0,
    updated: "1 week ago",
    color: "amber",
    status: "active",
  },
  {
    id: "qz_2vh7",
    title: "Modern Political Theory",
    course: "POL 150",
    author: "Dr. E. Vance",
    questions: 10,
    duration: 30,
    difficulty: "Introductory",
    tags: ["politics", "theory", "essay"],
    description: "Hobbes, Locke, Rousseau, Rawls — foundational readings.",
    assigned: 64,
    completed: 60,
    avgScore: 76.4,
    updated: "3 days ago",
    color: "blue",
    status: "active",
  },
  {
    id: "qz_9tg4",
    title: "Linear Algebra Review",
    course: "MATH 110",
    author: "Dr. R. Halverson",
    questions: 20,
    duration: 40,
    difficulty: "Introductory",
    tags: ["math", "vectors", "matrices"],
    description: "Eigenvalues, basis, rank, and null space.",
    assigned: 312,
    completed: 271,
    avgScore: 70.1,
    updated: "yesterday",
    color: "accent",
    status: "active",
  },
  {
    id: "qz_6kx2",
    title: "Cell Biology — Membranes",
    course: "BIO 240",
    author: "Dr. P. Okonkwo",
    questions: 15,
    duration: 25,
    difficulty: "Intermediate",
    tags: ["biology", "cells"],
    description: "Phospholipid bilayers, transport proteins, signaling.",
    assigned: 122,
    completed: 119,
    avgScore: 84.7,
    updated: "4 days ago",
    color: "amber",
    status: "draft",
  },
];

// The active assessment the learner is taking
const ACTIVE_QUIZ = {
  id: "qz_8sd1",
  title: "Algorithms — Graph Traversal",
  course: "CS 311",
  totalQuestions: 5,
  duration: 45,
  objectives: [
    "Distinguish BFS and DFS by traversal order and data-structure choice",
    "Reason about when a topological ordering exists and how to compute it",
    "Derive the time and space complexity of standard traversals from first principles",
    "Implement an iterative DFS that correctly handles cycles",
  ],
  questions: [
    {
      id: "q1",
      type: "mc",
      prompt: "Which traversal strategy visits all vertices at the current depth before moving deeper?",
      points: 2,
      options: [
        { id: "a", text: "Depth-first search (DFS)" },
        { id: "b", text: "Breadth-first search (BFS)" },
        { id: "c", text: "Dijkstra's algorithm" },
        { id: "d", text: "A* search" },
      ],
      correct: "b",
    },
    {
      id: "q2",
      type: "tf",
      prompt: "Topological sort is well-defined for any directed graph, including those with cycles.",
      points: 1,
      correct: false,
      explanation: "A topological ordering only exists for directed acyclic graphs (DAGs). Cycles make it impossible to linearly order vertices respecting all edges.",
    },
    {
      id: "q3",
      type: "short",
      prompt: "What is the time complexity of BFS on a graph with V vertices and E edges, using an adjacency list?",
      points: 2,
      correct: ["O(V+E)", "O(V + E)", "O(|V|+|E|)"],
    },
    {
      id: "q4",
      type: "code",
      prompt: "Complete the function to perform an iterative DFS that returns vertices in visit order. Assume `graph` is an adjacency-list dict.",
      points: 4,
      language: "python",
      starter: "def dfs(graph, start):\n    visited = set()\n    order = []\n    stack = [start]\n    while stack:\n        # your code here\n        pass\n    return order",
    },
    {
      id: "q5",
      type: "essay",
      prompt: "Compare BFS and DFS in terms of memory usage and the kinds of problems each is best suited for. Cite at least one concrete example for each.",
      points: 6,
      minWords: 80,
    },
  ],
};

// Past results for review
const LAST_ATTEMPT = {
  assessmentId: "qz_8sd1",
  assessmentTitle: "Algorithms — Graph Traversal",
  course: "CS 311",
  submitted: "Today, 14:22",
  duration: "31 min 04 sec",
  score: 11,
  total: 15,
  percent: 73.3,
  cohortAvg: 68.5,
  cohortPercentile: 72,
  answers: [
    { qid: "q1", correct: true,  points: 2, max: 2, type: "mc",    given: "Breadth-first search (BFS)", note: "Correct — BFS uses a FIFO queue." },
    { qid: "q2", correct: true,  points: 1, max: 1, type: "tf",    given: "False", note: "Topological sort requires a DAG." },
    { qid: "q3", correct: true,  points: 2, max: 2, type: "short", given: "O(V+E)", note: "Standard adjacency-list result." },
    { qid: "q4", correct: false, points: 2, max: 4, type: "code",  given: "(partial)", note: "Missing the unvisited check; revisits cycle vertices." },
    { qid: "q5", correct: false, points: 3, max: 6, type: "essay", given: "(102 words)", note: "Strong on memory comparison; weak on concrete examples." },
  ],
};

// Dashboard data
const PROGRESS_OVER_TIME = [
  { week: "W1", score: 58 }, { week: "W2", score: 62 }, { week: "W3", score: 61 },
  { week: "W4", score: 67 }, { week: "W5", score: 70 }, { week: "W6", score: 69 },
  { week: "W7", score: 74 }, { week: "W8", score: 78 }, { week: "W9", score: 76 },
  { week: "W10", score: 81 }, { week: "W11", score: 79 }, { week: "W12", score: 84 },
];

const SUBJECT_BREAKDOWN = [
  { subject: "Algorithms",     score: 73, attempts: 12 },
  { subject: "Economics",      score: 81, attempts: 8 },
  { subject: "Chemistry",      score: 67, attempts: 6 },
  { subject: "Mathematics",    score: 89, attempts: 14 },
  { subject: "Biology",        score: 71, attempts: 5 },
  { subject: "Political Sci.", score: 84, attempts: 4 },
];

const COHORT_DISTRIBUTION = [
  { bin: "0-50",   count: 3 },
  { bin: "50-60",  count: 7 },
  { bin: "60-70",  count: 14 },
  { bin: "70-80",  count: 22 },
  { bin: "80-90",  count: 18 },
  { bin: "90-100", count: 7 },
];

const ITEM_ANALYSIS = [
  { q: "Q1", topic: "BFS definition",      difficulty: 0.21, discrim: 0.41, correct: 79 },
  { q: "Q2", topic: "Topological sort",    difficulty: 0.34, discrim: 0.52, correct: 66 },
  { q: "Q3", topic: "BFS complexity",      difficulty: 0.18, discrim: 0.38, correct: 82 },
  { q: "Q4", topic: "Iterative DFS code",  difficulty: 0.72, discrim: 0.61, correct: 28 },
  { q: "Q5", topic: "BFS vs DFS essay",    difficulty: 0.55, discrim: 0.44, correct: 45 },
];

// EXAMS — composed assessments that bundle multiple assessments
const EXAMS = [
  {
    id: "ex_cs311_mid",
    title: "CS 311 — Midterm",
    course: "CS 311",
    author: "Prof. M. Iwata",
    composedBy: "Prof. M. Iwata",
    method: "manual",
    status: "scheduled",
    open: "Apr 22, 2026 · 09:00",
    close: "Apr 22, 2026 · 11:00",
    duration: 120,
    totalPoints: 60,
    passing: 65,
    sections: [
      { id: "s1", assessmentId: "qz_8sd1", title: "Graph traversal",         weight: 30, items: 12, mix: "MC · short · code" },
      { id: "s2", assessmentId: "qz_9tg4", title: "Linear algebra review",   weight: 20, items: 8,  mix: "MC · short" },
      { id: "s3", assessmentId: "qz_2vh7", title: "Complexity short answer", weight: 10, items: 4,  mix: "short" },
    ],
    assigned: 86,
    completed: 0,
    avgScore: null,
    description: "Two-hour midterm composed of three sections covering graphs, linear algebra prerequisites, and complexity analysis.",
    objectives: [
      "Apply BFS, DFS, and topological sort to canonical problem instances",
      "Translate between matrix, vector, and basis representations of a linear system",
      "Argue informally about the time and space complexity of graph algorithms",
      "Recognize when an algorithm's correctness hinges on cycle handling",
    ],
    tags: ["midterm", "proctored", "in-person"],
  },
  {
    id: "ex_chem_unit2",
    title: "CHEM 220 — Unit II Assessment",
    course: "CHEM 220",
    author: "Dr. P. Okonkwo",
    composedBy: "TA-Assist",
    method: "agent",
    status: "active",
    open: "Apr 14, 2026 · 00:00",
    close: "Apr 21, 2026 · 23:59",
    duration: 90,
    totalPoints: 45,
    passing: 60,
    sections: [
      { id: "s1", assessmentId: "qz_4mp9", title: "Stereochemistry",  weight: 20, items: 12, mix: "MC · short" },
      { id: "s2", assessmentId: "qz_6kx2", title: "Membranes (xref)", weight: 15, items: 8,  mix: "MC · TF" },
      { id: "s3", assessmentId: "qz_4mp9", title: "Synthesis problems", weight: 10, items: 4, mix: "essay · short" },
    ],
    assigned: 203,
    completed: 142,
    avgScore: 71.8,
    description: "Open-window assessment with adaptive difficulty. Auto-composed by TA-Assist using the unit 2 syllabus and 3 weeks of attempt data.",
    objectives: [
      "Assign R / S configuration to a stereocenter from a 2-D structure",
      "Predict the major product of an SN2 vs SN1 reaction on a chiral substrate",
      "Interpret a polarimetry reading and link it to enantiomeric excess",
      "Map a transport protein's function onto membrane biology fundamentals",
    ],
    tags: ["open-window", "adaptive", "agent-composed"],
  },
  {
    id: "ex_econ_final",
    title: "ECON 204 — Final Exam",
    course: "ECON 204",
    author: "Dr. R. Halverson",
    composedBy: "Dr. R. Halverson",
    method: "manual",
    status: "draft",
    open: "Jun 03, 2026 · 13:00",
    close: "Jun 03, 2026 · 16:00",
    duration: 180,
    totalPoints: 100,
    passing: 70,
    sections: [
      { id: "s1", assessmentId: "qz_3kf2", title: "Monetary policy",  weight: 35, items: 14, mix: "MC · short · essay" },
      { id: "s2", assessmentId: "qz_3kf2", title: "Fiscal multipliers", weight: 25, items: 8, mix: "short · essay" },
      { id: "s3", assessmentId: "qz_3kf2", title: "Case analysis",     weight: 40, items: 2, mix: "essay" },
    ],
    assigned: 142,
    completed: 0,
    avgScore: null,
    description: "Cumulative final exam. Three-hour cap with one comprehensive case-analysis essay worth 40% of the grade.",
    objectives: [
      "Trace the transmission of a policy-rate change through to inflation and output",
      "Compute and interpret fiscal multipliers under different consumption assumptions",
      "Construct a coherent argument linking historical monetary regimes to outcomes",
      "Evaluate a case study with explicit appeal to course models and primary data",
    ],
    tags: ["final", "proctored", "cumulative"],
  },
  {
    id: "ex_diag_cs",
    title: "CS — Capability Diagnostic",
    course: "Self-paced",
    author: "Harus diagnostics",
    composedBy: "TA-Assist",
    method: "agent",
    status: "active",
    open: "Always",
    close: "Always",
    duration: 60,
    totalPoints: 30,
    passing: 50,
    sections: [
      { id: "s1", assessmentId: "qz_8sd1", title: "Algorithms baseline", weight: 12, items: 5, mix: "MC · code" },
      { id: "s2", assessmentId: "qz_9tg4", title: "Math baseline",       weight: 10, items: 6, mix: "short" },
      { id: "s3", assessmentId: "qz_6kx2", title: "Reasoning",           weight: 8,  items: 4, mix: "MC · short" },
    ],
    assigned: 412,
    completed: 287,
    avgScore: 64.2,
    description: "Cross-subject diagnostic that places learners and recommends a study plan. Composed nightly from the question bank.",
    objectives: [
      "Locate your current mastery band across algorithms, math, and reasoning",
      "Surface specific topic gaps with question-level evidence",
      "Produce a personalized study plan calibrated to your starting point",
    ],
    tags: ["diagnostic", "always-on", "adaptive"],
  },
];

// MCP-style tool descriptors for the agent panel
const AGENT_TOOLS = [
  {
    name: "assessment.import",
    desc: "Create a new assessment from JSON or Markdown source.",
    inputs: ["source: string", "format: 'json' | 'md'", "courseId?: string"],
    returns: "{ assessmentId, questionCount, warnings[] }",
    method: "POST",
    path: "/v1/assessments",
  },
  {
    name: "assessment.generate",
    desc: "Generate a assessment from a source document URL or text.",
    inputs: ["source: string", "questionCount: int", "types?: string[]", "difficulty?: string"],
    returns: "{ assessmentId, questions[] }",
    method: "POST",
    path: "/v1/assessments/generate",
  },
  {
    name: "attempt.get",
    desc: "Fetch a single learner's answers and per-item scoring for a assessment attempt.",
    inputs: ["attemptId: string"],
    returns: "{ user, score, answers[], rubric[] }",
    method: "GET",
    path: "/v1/attempts/{id}",
  },
  {
    name: "stats.cohort",
    desc: "Aggregate stats for a assessment across a cohort: averages, distribution, item analysis.",
    inputs: ["assessmentId: string", "cohortId?: string", "window?: 'last30d' | 'all'"],
    returns: "{ avg, median, distribution[], items[] }",
    method: "GET",
    path: "/v1/assessments/{id}/stats",
  },
  {
    name: "feedback.send",
    desc: "Push a personalized reminder or feedback message to a learner.",
    inputs: ["userId: string", "channel: 'in-app' | 'email'", "body: string", "linkAssessmentId?: string"],
    returns: "{ messageId, queuedAt }",
    method: "POST",
    path: "/v1/messages",
  },
  {
    name: "exam.compose",
    desc: "Compose an exam by ordering existing assessments into weighted sections.",
    inputs: ["title: string", "sections: { assessmentId, weight, items? }[]", "duration: int", "window?: { open, close }"],
    returns: "{ examId, totalPoints, sections[], warnings[] }",
    method: "POST",
    path: "/v1/exams",
  },
  {
    name: "exam.get",
    desc: "Fetch an exam's structure, attempt window, and per-section item counts.",
    inputs: ["examId: string"],
    returns: "{ exam, sections[], cohortStatus }",
    method: "GET",
    path: "/v1/exams/{id}",
  },
  {
    name: "exam.stats",
    desc: "Aggregate exam-level stats — per-section averages, pass rate, time-to-complete.",
    inputs: ["examId: string", "cohortId?: string"],
    returns: "{ passRate, sectionAvgs[], timeP50, timeP95 }",
    method: "GET",
    path: "/v1/exams/{id}/stats",
  },
  {
    name: "plan.create",
    desc: "Compose a study plan derived from a learner's attempt history.",
    inputs: ["userId: string", "goal: string", "lookbackDays?: int"],
    returns: "{ planId, steps[], estimatedHours }",
    method: "POST",
    path: "/v1/plans",
  },
];

const API_KEYS = [
  { id: "key_live_3f", label: "GraderBot — production", prefix: "hk_live_3fY9…ax2P", created: "Mar 12, 2026", lastUsed: "12 min ago", scopes: ["assessment.read", "attempt.read", "stats.read"] },
  { id: "key_live_8a", label: "TA-Assist (MCP)",         prefix: "hk_live_8aQ2…m1Vk", created: "Jan 04, 2026", lastUsed: "2 hours ago",   scopes: ["assessment.write", "attempt.read", "feedback.write"] },
  { id: "key_test_z1", label: "Local dev",               prefix: "hk_test_z1Lo…7nKd", created: "Feb 22, 2026", lastUsed: "3 days ago",    scopes: ["*"] },
];

const SAMPLE_IMPORT = `{
  "title": "Photosynthesis — Light Reactions",
  "course": "BIO 110",
  "questions": [
    {
      "type": "mc",
      "prompt": "Which complex splits water in PSII?",
      "options": ["OEC", "Cytochrome b6f", "ATP synthase", "Plastocyanin"],
      "correct": 0,
      "points": 2
    },
    {
      "type": "short",
      "prompt": "Name the final electron acceptor in the light reactions.",
      "correct": ["NADP+", "NADP\\u207a"],
      "points": 2
    }
  ]
}`;

Object.assign(window, {
  QUIZZES, EXAMS, ACTIVE_QUIZ, LAST_ATTEMPT,
  PROGRESS_OVER_TIME, SUBJECT_BREAKDOWN, COHORT_DISTRIBUTION, ITEM_ANALYSIS,
  AGENT_TOOLS, API_KEYS, SAMPLE_IMPORT,
});
