//! OpenAPI 3 specification for the current learner contract.

use utoipa::OpenApi;

use crate::http::{
    admin::{
        AdminHealthResponse, AuditLogEntry, ListAuditLogsResponse, ListUsersResponse,
        PatchUserAdminBody, UpdateSettingsBody,
    },
    analytics::{
        LearnerAnalyticsResponse, MasteryPoint, RatioMetric, ReviewHistoryPoint, StreakMetric,
        TimeMetric,
    },
    assessments::{
        AssessmentActivityQuery, AssessmentItemBody, AssessmentOptionResponse,
        AssessmentQuestionResponse, AssessmentResponse, CreateAssessmentBody,
    },
    attempts::{AttemptItemResponse, AttemptResponse, SaveAnswerBody, StartAttemptBody},
    auth::{AuthResponse, LoginBody, RegisterBody, UserInfo},
    citations::{CitationResponse, CreateCitationBody},
    deep_dives::{CreateDeepDiveBody, DeepDiveActivityQuery, DeepDiveResponse},
    generation::{GenerationRunResponse, StartGenerationRunBody, TransitionGenerationRunBody},
    learning::{
        FinishLearningSessionBody, LearningActivityResponse, LearningGoalResponse,
        LearningJourneyResponse, LearningJourneySummaryResponse, LearningObjectiveResponse,
        LearningRecommendationResponse, LearningResponseBody, LearningSessionResponse,
    },
    me::MeResponse,
    notes::{CreateNoteBody, NoteResponse, UpdateNoteBody},
    onboarding::{
        NativeJourneyCatalogResponse, NativeJourneyContentReviewResponse,
        NativeJourneySourceResponse, PreviewActivityResponse, PreviewLearningBody,
        PreviewLearningResponse, PreviewObjectiveResponse, StartLearningBody,
        StartLearningResponse,
    },
    portability::{ImportReceipt, JourneyExportManifest},
    progress::{
        EvidenceBody, EvidenceResponse, ObjectiveActivityBody, RecommendationBody,
        RecommendationResponse, SnapshotResponse, StreakBody, StreakResponse,
        TimelineEventResponse,
    },
    questions::{CreateQuestionBody, QuestionResponse},
    reviews::{DueReviewQuery, RateReviewBody, ReviewItemResponse, SeedReviewBody},
    sources::{ImportSourceBody, SourceImportRunResponse, SourceSnapshotResponse},
    tasks::{
        ReviewTaskOutcome, ReviewTaskSubmissionBody, ReviseTaskSubmissionBody,
        StartTaskSubmissionBody, TaskSubmissionResponse,
    },
    variants::{PublishVariantBody, RequestVariantBody, VariantResponse},
};

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::http::auth::register,
        crate::http::auth::login,
        crate::http::auth::logout,
        crate::http::onboarding::start_learning,
        crate::http::onboarding::preview_learning,
        crate::http::onboarding::list_native_journeys,
        crate::http::learning::get_journey,
        crate::http::learning::list_journeys,
        crate::http::learning::create_chapter,
        crate::http::learning::create_activity,
        crate::http::learning::submit_activity_for_review,
        crate::http::learning::publish_activity,
        crate::http::learning::get_learning_session,
        crate::http::learning::finish_learning_session,
        crate::http::learning::start_activity,
        crate::http::learning::get_activity_content,
        crate::http::learning::author_activity_content,
        crate::http::learning::author_activity_rubric,
        crate::http::questions::create_question,
        crate::http::questions::create_question_version,
        crate::http::questions::get_question_version,
        crate::http::assessments::create_assessment,
        crate::http::assessments::get_assessment_for_activity,
        crate::http::assessments::get_assessment,
        crate::http::attempts::start_attempt,
        crate::http::attempts::get_attempt,
        crate::http::attempts::list_journey_attempts,
        crate::http::attempts::save_answer,
        crate::http::attempts::finish_attempt,
        crate::http::progress::record_evidence,
        crate::http::progress::snapshot,
        crate::http::progress::recommend,
        crate::http::progress::record_streak,
        crate::http::progress::list_streaks,
        crate::http::progress::list_timeline,
        crate::http::reviews::seed,
        crate::http::reviews::list_due,
        crate::http::reviews::rate,
        crate::http::sources::import,
        crate::http::sources::list_imports,
        crate::http::sources::list,
        crate::http::sources::get_one,
        crate::http::citations::create_citation,
        crate::http::citations::list_citations,
        crate::http::citations::get_citation,
        crate::http::notes::create_note,
        crate::http::notes::list_notes,
        crate::http::notes::update_note,
        crate::http::notes::delete_note,
        crate::http::portability::export_journey,
        crate::http::portability::import_journey,
        crate::http::analytics::get_analytics,
        crate::http::variants::request_variant,
        crate::http::variants::list_variants,
        crate::http::variants::publish_variant,
        crate::http::deep_dives::create,
        crate::http::deep_dives::get_for_activity,
        crate::http::deep_dives::get_one,
        crate::http::generation::start,
        crate::http::generation::get_one,
        crate::http::generation::transition,
        crate::http::me::get_me,
        crate::http::admin::list_users,
        crate::http::admin::patch_user_admin,
        crate::http::admin::list_audit_logs,
        crate::http::admin::get_admin_health,
        crate::http::admin::get_settings,
        crate::http::admin::put_settings,
        crate::http::tasks::start_submission,
        crate::http::tasks::get_submission,
        crate::http::tasks::revise_submission,
        crate::http::tasks::list_pending_submissions,
        crate::http::tasks::submit_submission,
        crate::http::tasks::review_submission
    ),
    components(schemas(
        crate::domain::error::ApiError,
        crate::domain::error::FieldError,
        crate::domain::user::Role,
        crate::domain::user::User,
        LoginBody,
        AuthResponse,
        RegisterBody,
        UserInfo,
        PreviewLearningBody,
        NativeJourneyCatalogResponse,
        NativeJourneySourceResponse,
        NativeJourneyContentReviewResponse,
        PreviewLearningResponse,
        PreviewObjectiveResponse,
        PreviewActivityResponse,
        StartLearningBody,
        StartLearningResponse,
        MeResponse,
        LearningGoalResponse,
        LearningJourneyResponse,
        LearningJourneySummaryResponse,
        LearningRecommendationResponse,
        LearningObjectiveResponse,
        LearningActivityResponse,
        LearningSessionResponse,
        FinishLearningSessionBody,
        LearningResponseBody,
        CreateQuestionBody,
        QuestionResponse,
        CreateAssessmentBody,
        AssessmentActivityQuery,
        AssessmentQuestionResponse,
        AssessmentOptionResponse,
        AssessmentItemBody,
        AssessmentResponse,
        StartAttemptBody,
        SaveAnswerBody,
        AttemptResponse,
        AttemptItemResponse,
        EvidenceBody,
        EvidenceResponse,
        ObjectiveActivityBody,
        RecommendationBody,
        RecommendationResponse,
        SnapshotResponse,
        StreakBody,
        StreakResponse,
        TimelineEventResponse,
        SeedReviewBody,
        DueReviewQuery,
        RateReviewBody,
        ReviewItemResponse,
        ImportSourceBody,
        SourceSnapshotResponse,
        SourceImportRunResponse,
        CreateCitationBody,
        CitationResponse,
        CreateNoteBody,
        UpdateNoteBody,
        NoteResponse,
        JourneyExportManifest,
        ImportReceipt,
        LearnerAnalyticsResponse,
        RatioMetric,
        StreakMetric,
        TimeMetric,
        MasteryPoint,
        ReviewHistoryPoint,
        RequestVariantBody,
        PublishVariantBody,
        VariantResponse,
        CreateDeepDiveBody,
        DeepDiveResponse,
        DeepDiveActivityQuery,
        GenerationRunResponse,
        StartGenerationRunBody,
        TransitionGenerationRunBody,
        ListUsersResponse,
        PatchUserAdminBody,
        ListAuditLogsResponse,
        AuditLogEntry,
        AdminHealthResponse,
        UpdateSettingsBody,
        crate::settings::EffectiveSettings,
        crate::settings::RateLimitSettings,
        crate::settings::TierLimit,
        StartTaskSubmissionBody,
        TaskSubmissionResponse,
        ReviseTaskSubmissionBody,
        ReviewTaskOutcome,
        ReviewTaskSubmissionBody
    )),
    info(
        title = "ame API",
        version = "0.3.1",
        description = "ame — an agent-friendly learning API with one owner-scoped learner model."
    )
)]
pub struct ApiDoc;

pub fn openapi_yaml() -> String {
    ApiDoc::openapi()
        .to_yaml()
        .expect("OpenAPI spec serializes to YAML")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn openapi_spec_is_current() {
        let generated = openapi_yaml();
        let committed = fs::read_to_string("openapi.yaml").expect("failed to read openapi.yaml");
        if generated.trim() != committed.trim() {
            eprintln!("--- generated ---\n{generated}\n--- committed ---\n{committed}");
            panic!("openapi.yaml is out of date with the source. Regenerate via `make openapi`.");
        }
    }
}
